### PR TITLE
Updated the .html files by running build.py script

### PR DESCRIPTION
**Pull request by sammyshj**
Changes done in the PR:
* Updated all the .html files by running the build.py script

The changes are required so that the pages work good in the Safari extension. The link to the Safari extension submodule update: https://github.com/privly/privly-safari/pull/31

### CODE REVIEW

**Comment by smcgregor** [comment]
Let's hold off on updating the HTML until gsoc-develop is merged since the gsoc-develop HTML is for privly-web. Either that, or we need to create a safari-master branch, but I would rather not create another extension branch if/until it becomes necessary.

**Comment by sammyshj** [comment]
If the HTML files are not updated then, the Safari extension cannot be integrated with the changes made in https://github.com/privly/privly-applications/pull/250

**Comment by smcgregor** [comment]
Why not? Build the files locally.

**Comment by smcgregor** [comment]
It should only matter when we tag the commit and push out a version to users.

**Comment by sammyshj** [comment]
I have updated the submodule in the Safari extension that refer to the changes done in this PR, https://github.com/privly/privly-safari/pull/31
Should I create a new branch in the privly-applications repo of my fork and refer to the changes there then?

**Comment by smcgregor** [comment]
Why not set the commit to the current version of gsoc-develop and build the files locally until gsoc-develop is merged?

**Comment by sammyshj** [comment]
Alright, that works well! Then the further changes in the Safari extension will be based on the latest commit of the gsoc-develop branch.
Closing this PR and https://github.com/privly/privly-safari/pull/31 then.

**Pull request closed without merging**
