### PR TITLE
Wrap an immediate function invocation in parens to improve code quality

### PR DESCRIPTION
**Pull request by ujjwalwahi**
Improves the code quality of *Message/js/base64.js* by wrapping an immediate function invocation in parens

### CODE REVIEW

**Comment by spectralsun** [comment]
:+1:

**Comment by irdan** [comment]
Since `base64.js` is part of the ZeroBin library, I'm not sure we want to start modifying it.  Unless we want to either submit this upstream or are openly okay with diverging from the fork, I'm -1 to merging this.

**Comment by smcgregor** [comment]
I didn't put it in the vendor directory, so I think it is fair game. The only issue I can think of is that Mozilla _may_ want to verify its integrity against the source before they will distribute the extension. However, I don't think this is actually an issue here since the ZeroBin author seems to have already modified it.

Regardless, this is a recommendation of CodeClimate? I am surprised it wants the extra parens.

@ujjwalwahi: I am +1 if you link to the recommendation on CodeClimate.

**Comment by smcgregor** [comment]
For reference, this is the build on my fork. https://travis-ci.org/smcgregor/privly-applications/builds/53004176

**Comment by ujjwalwahi** [comment]
Link to CodeClimate recommendation https://codeclimate.com/github/privly/privly-applications/Message/js/base64.js

**Comment by smcgregor** [comment]
Sound reasoning, thanks!

**Pull request merged**
