### PR TITLE
Fix Code Climate issues in parameters.js

### PR DESCRIPTION
**Pull request by d356**
Filter properties in the for loop, add a semicolon, and make “key” a local variable.

https://codeclimate.com/github/privly/privly-applications/shared/javascripts/parameters.js

### CODE REVIEW

**Comment by smcgregor** [comment]
Good work. It is in the review queue.

Have you run Karma tests for this yet?

**Comment by d356** [comment]
Thanks. I set up Karma and the tests seem to pass for me.

**Comment by smcgregor** [comment]
It is [failing on TravisCI](https://travis-ci.org/smcgregor/privly-applications/builds/52995569) for me, although I am uncertain why since I don't see a syntactic issue where it is finding one.

**Comment by d356** [comment]
The tests failed for me in the same way at first, so I added the second commit, which fixed the "Unexpected token" errors.

**Comment by smcgregor** [comment]
yep, it looks like I pulled between the two commits. I am re-running now.

**Pull request merged**
