### PR TITLE
Added sauce_safari_web

### PR DESCRIPTION
**Pull request by sammyshj**
Added sauce_safari_web for running the selenium tests on SauceLabs

### CODE REVIEW

**Comment by smcgregor** [comment]
Can you link to this running on SauceLabs? They have a video playback feature.

**Comment by sammyshj** [comment]
@smcgregor Yes, the tests still dont run currently and I am working on that right now. Once the tests run good, I will comment the link on this PR.

**Comment by sammyshj** [comment]
@smcgregor The tests run successfully now on SauceLabs. The test-run can be seen at https://saucelabs.com/tests/29a8893777de46fc88eeb7fed7c8b58a
Should I squash the commits into one for the PR to be merged?

**Comment by smcgregor** [comment]
Yes, unless you want to add TravisCI support first.

**Comment by sammyshj** [comment]
@smcgregor I have squashed the commits into one. I was planning on implementing safari_extension and sauce_safari_extension next and then finally adding TravisCI support to run the tests.

**Pull request merged**
