### PR TITLE
Updated the cleartext element

### PR DESCRIPTION
**Pull request by opg7371**
Updated the size of cleartext element in the top.css file
Please review .....:)
#317

### CODE REVIEW

**Comment by smcgregor** [comment]
Hi Piyush, thanks for tackling this!

Can you post a screen capture and if it looks good I'll give it a test on my laptop and phone?

**Comment by opg7371** [comment]
sorry for the delay..
cleartext-content
Too much big font will too look like a mess.
Thus i kept it normal.
Please tell me if i should increase the size....

However for a large font-size i have created a pull request....
please review it too........https://github.com/privly/privly-applications/pull/346

**Comment by smcgregor** [comment]
Please open a single pull request for each issue and iterate based on comments until we merge it. If you want to show an alternative font, just post a second picture and describe it.

**Comment by smcgregor** [comment]
I think the PR with the larger font might be better, but I would need to see it on a smaller screen (a phone). It might be good to conditionally set the font size based on the screen resolution (using `@media` rules or another method).

**Comment by opg7371** [comment]
cleartext-min
This is how it looks on phone with a larger font(23px).
Yes i do agree with you regarding the font-size should change based on screen resolution

**Comment by smcgregor** [comment]
I think the larger font looks better.

**Comment by opg7371** [comment]
This one consist of the larger font-size (23px) and  looks like this in the browser.
content-large

Please review...:)

**Comment by smcgregor** [comment]
Looks good. Can you squash your commits into a single commit and I will merge?

**Comment by opg7371** [comment]
Sir i guess i did it wrong...sorry 
will be soon updating it now.....
Ignore this squash of commits

**Comment by opg7371** [comment]
A more Updated pull request here ....#354

**Pull request closed without merging**
