### PR TITLE
Updated SJCL to version 1.0.2

### PR DESCRIPTION
**Pull request by anmoljagetia**
Updated the SJCL library from Stanford University to the latest version i.e. 1.0.2. Fixes issue #146.

### CODE REVIEW

**Comment by smcgregor** [comment]
Have you run all the Karma tests on this yet?

**Comment by smcgregor** [comment]
You should also update [this file](https://github.com/privly/privly-applications/blob/master/vendor/README.md).

**Comment by anmoljagetia** [comment]
Yes I ran all the test, they all pass :)

**Comment by smcgregor** [comment]
Strange, when I compare your PR's version of SJCL, to the canonical version I dropped in place of it, I get:

> diff --git a/vendor/sjcl.js b/vendor/sjcl.js
> old mode 100644
> new mode 100755

But **only** if I grab the ZIP version. The tarred version shows no difference.

Quirks.

**Pull request merged**
