### PR TITLE
Update split image branch to include latest commits

### PR DESCRIPTION
**Pull request by anmoljagetia**
in reference to #189.

### CODE REVIEW

**Comment by anmoljagetia** [comment]
This is a big commit, I hope there are no more merge conflicts left, I tried running the tests, and one of them failed, with the message *Chrome 41.0.2272 (Linux) Options Suite tests localStorage bindings FAILED*, can you please help me fix it ?

**Comment by smcgregor** [comment]
I'm on my phone so I can't help much here. I can say there is an open issue
for that test failure.

**Comment by anmoljagetia** [comment]
Thanks for the help, I'll look into it.

**Comment by smcgregor** [comment]
Here is the issue for the non-deterministic test fail: https://github.com/privly/privly-applications/issues/188

**Comment by smcgregor** [comment]
Closing for https://github.com/privly/privly-applications/pull/201

**Pull request closed without merging**
