### PR TITLE
Add SplitImage App to New Branch

### PR DESCRIPTION
**Pull request by smcgregor**
It was too much code and too many commits to understand and review, so I updated the SplitImage experimental app myself in a more compact way. Here I created a fresh branch from master and merged in the experimental app, instead of the other way around. This makes it *much* tighter.

I am going to leave this open for a day for comment for people working on other updates to the experimental app.

Please note that I did not build the HTML for the pull request. This also made it easier to review. You **need to run the build script to review this**: `python build.py -r experimental`.

#197 
#198

### CODE REVIEW

**Comment by vatsalj** [comment]
@smcgregor Any estimate as to when this will be merged? I cloned your repository(smcgregor:gsoc-SplitImage) and built the files. So far it seems to be working fine on my locally deployed content server. As soon as the request is merged, there are a few short-term goals I'd like to achieve, including:

1. Support for multiple files which will also include the handling errors (file size limit, file type mismatch etc)
2. Upload link for each file when multiple files are selected.
3. Fix minor issues such as error message showing up along with Preview div (attached screenshot).
4. Unit tests

Long term goals include making the application production ready, end-to-end.

Screenshots:
3. 
image

**Comment by smcgregor** [comment]
@vatsalj Don't work on multiple files _yet:_ remember this is intended to be viewed injected into an application. Multiple images breaks the correspondence between single link and single image which will likely cause problems that are best solved after single images are working properly.

**Comment by vatsalj** [comment]
@smcgregor : The way I was thinking of implementing it was that users can select multiple files at a time, however, after the injected application has base64 encoded them, user will have to individually use upload and get link for different file. Something like this (please excuse the bad mockup :) ):

File Name | Upload | Link
-------------| ----------| -------
AudioMessage1.mp3  | Upload and get link | link obtained after uploading 1st message
AudioMessage2.mp3| Upload and get link | link obtained after uploading 2nd message

**You're right though**, application should be working properly for single images first. Multiple images support can be added later once that is done.

So, since multiple images is not a priority right now, what can I work on in this? I was looking into the threat models for this application. If you have something else in mind, which can help with this application, please let me know. I'll get started on it at the earliest.

**Comment by smcgregor** [comment]
I think unit and integration tests are a good place to start.

**Pull request merged**
